### ISSUE TITLE
Storage-buffer-size "infinity" breaks job monitoring for WLCG platform simulation

### ISSUE THREAD

**Issue by HerrHorizontal** [HEPCompSim/DCSim#55]
When executing a simulation for the WLCG platform with `--storage-buffer-size inf` the monitor CSV output file containing the simulated jobs' quantities gets only filled with the header.

**Comment by henricasanova** [comment]
I'll investigate.

**Comment by henricasanova** [comment]
I am not able to reproduce this error... would you have a particular command-line? I've tried several runs and passing 'inf' (or 'infinity') gives me no error and the same results as passing 100000000000...

**Comment by henricasanova** [comment]
Thanks! I am able to reproduce the issue, and it happens for a buffer size = `inf`, but also for a buffer size = `1000000000`. So it's not something special about `inf` it's something else.  BUT, when upgrading WRENCH to the current master, and fixing the code to compile due to the API change, it all works. So it **was** a bug, but given the major WRENCH refactoring, which is all about the storage service, it all works. 

If you upgrade WRENCH/SimGrid, then merge the DCSim `main` branch into the `scenario/wlcg` branch, the bug will magically disappear :)

**Comment by HerrHorizontal** [comment]
Nice to hear. Is there a specific version of WRENCH and SimGrid I have to checkout? Or are both the `main` branches fine?

**Comment by HerrHorizontal** [comment]
I have tried it with the latest commits on SimGrid and WRENCH and can confirm that it solves the issue. Thank you very much!
